AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  provider:
    Type: String
Resources:
  MyCustomActionType:
    Type: "AWS::CodePipeline::CustomActionType"
    Properties:
      Category: Build
#You must logout and log into the Console to see this new Build Provider in CodePipeline :(
      Provider: !Ref provider
      Version: 1
      ConfigurationProperties:
        - Description: "my Server URL description"
          Key: true
          Name: "ServerURL"
          Queryable: false
          Required: true
          Secret: false
          Type: String
        - Description: "my Project Name description"
          Key: true
          Name: ProjectName
          Queryable: true
          Required: true
          Secret: false
          Type: String
      InputArtifactDetails:
        MaximumCount: 1
        MinimumCount: 1
      OutputArtifactDetails:
        MinimumCount: 1
        MaximumCount: 1
      Settings:
        EntityUrlTemplate: "http://{Config:ServerURL}:8080/job/{Config:ProjectName}/"
        ExecutionUrlTemplate: "http://{Config:ServerURL}:8080/job/{Config:ProjectName}/lastSuccessfulBuild/{ExternalExecutionId}/"
Outputs:
  StackProvider:
    Description: The Provider name input parm value
    Value: !Ref provider
    Export:
#      Name: !Sub "${AWS::StackName}-provider" This !Sub caused cf1.json to fail :(
      Name: "pfeiffer4building0-provider"

