AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  githubpassword:
    Type: String
  jenkinsurl:
    Type: String
  provider:
    Type: String
Resources:
  Vake:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Type: S3
        Location: "codepipeline-us-west-2-510060297905"
      Name: Fri8
      RoleArn: "arn:aws:iam::994238729631:role/AWS-CodePipeline-Service"
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: craigwongva
                Repo: "aws-code-deploy-linux"
                PollForSourceChanges: true
                Branch: master
                OAuthToken: !Ref githubpassword
              OutputArtifacts:
                - Name: MyApp
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: Custom
                Version: 1
                Provider: !Ref provider
#                Provider: !ImportValue pfeiffer4building0-provider
              Configuration:
                ProjectName: BuildProject
                ServerURL: !Ref jenkinsurl
#                ServerURL: !ImportValue pfeiffer4building1-PublicIp
              InputArtifacts:
                - Name: MyApp
              OutputArtifacts:
                - Name: MyAppBuild
              RunOrder: 1
        - Name: Staging
          Actions:
            - Name: DemoAppInstances
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: Demo4App
                DeploymentGroupName: DemoAppInstances
              InputArtifacts:
                - Name: MyAppBuild
              RunOrder: 1
