AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  githubpassword:
    Type: String
Resources:
  MyCustomActionType: 
    Type: "AWS::CodePipeline::CustomActionType"
    Properties: 
      Category: Build
#You must logout and log into the Console to see this new Build Provider in CodePipeline :(
      Provider: JenkinsFri3
      Version: 1
      ConfigurationProperties: 
        - Description: "my Server URL description"
          Key: true
          Name: "ServerURL"
          Queryable: false
          Required: true
          Secret: false
          Type: String
        - Description: "my Project Name description"
          Key: true
          Name: ProjectName
          Queryable: true
          Required: true
          Secret: false
          Type: String
      InputArtifactDetails: 
        MaximumCount: 1
        MinimumCount: 1
      OutputArtifactDetails: 
        MinimumCount: 1
        MaximumCount: 1
      Settings: 
        EntityUrlTemplate: "http://35.165.171.217:8080/job/{Config:ProjectName}/"
        ExecutionUrlTemplate: "http://35.165.171.217:8080/job/{Config:ProjectName}/lastSuccessfulBuild/{ExternalExecutionId}/"
  Vake:
    Type: "AWS::CodePipeline::Pipeline"
    DependsOn: MyCustomActionType
    Properties:
      ArtifactStore:
        Type: S3 
        Location: "codepipeline-us-west-2-510060297905"
      Name: Fri8 
      RoleArn: "arn:aws:iam::994238729631:role/AWS-CodePipeline-Service"
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: craigwongva 
                Repo: "aws-code-deploy-linux" 
                PollForSourceChanges: true 
                Branch: master 
                OAuthToken: !Ref githubpassword
              OutputArtifacts:
                - Name: MyApp
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: Custom 
                Version: 1 
                Provider: JenkinsFri3
              Configuration:
                ProjectName: BuildProject
                ServerURL: dummy
              InputArtifacts:
                - Name: MyApp
              OutputArtifacts:
                - Name: MyAppBuild
              RunOrder: 1
        - Name: Staging
          Actions:
            - Name: DemoAppInstances
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: Demo4App
                DeploymentGroupName: DemoAppInstances
              InputArtifacts:
                - Name: MyAppBuild
              RunOrder: 1

